'use strict'

/** @type {import('@adonisjs/lucid/src/Schema')} */
const Schema = use('Schema')

class MessageSchema extends Schema {
  up () {
    this.create('messages', (table) => {
      table.increments()
      table.integer('order_id').nullable()
      table.integer('from_id').nullable()
      table.integer('to_id').nullable()
      table.text('from_user_data').nullable()
      table.text('to_user_data').nullable()
      table.boolean('to_all').defaultTo(false)
      table.string('title').comment('Autogenerated title (except for admin)').notNullable()
      table.text('description').comment('Message info details').notNullable()
      table.timestamps()
    })
  }

  down () {
    this.drop('messages')
  }
}

module.exports = MessageSchema
